# Generated by Django 3.2 on 2023-04-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_title_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'Пользователь с таким именем уже существует.'}, max_length=150, null=True, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
